spring:
  datasource:
    url: jdbc:mysql://localhost:3306/walletdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: walletuser
    password: walletpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update          # auto-creates/updates tables on startup
    show-sql: true              # prints SQL to console (great for learning)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.wallet.api: DEBUG       # verbose logging for your own code
    org.hibernate.SQL: DEBUG
